### ISSUE TITLE
Ants get stuck at walls / corners (see attached image)

### ISSUE THREAD

**Issue by shaief** [jywarren/antfarm#1]
![ant_farm_-_2015-08-04_09 24 23](https://cloud.githubusercontent.com/assets/899702/9054484/a32aa96e-3a8a-11e5-8feb-80f05b494a34.png)

**Comment by shaief** [comment]
And after two hours:
![ant_farm_-_2015-08-04_11 12 07](https://cloud.githubusercontent.com/assets/899702/9056160/aa70050c-3a99-11e5-8ee7-b365a5f7f880.png)

**Comment by shaief** [comment]
After 5 hours (since opening this issue):
![ant_farm_-_2015-08-04_14 19 24](https://cloud.githubusercontent.com/assets/899702/9059570/d2b11ca8-3ab3-11e5-801c-3350be70df71.png)

**Comment by shaief** [comment]
After 7 hours (since opening this issue):
![ant_farm_-_2015-08-04_16 05 17](https://cloud.githubusercontent.com/assets/899702/9061182/9ed74650-3ac2-11e5-8bf7-a17586f01102.png)

**Comment by jywarren** [comment]
Haha glad to hear from you Shai! They are just so primitive that they don't
know there's a wall, and they keep trying to move forward.

I'm designing a class around them for ~12 yr olds where this is the first
version and we add behaviors and complexity as we go.

**Comment by shaief** [comment]
Yeah well... i knew it's a playground, but thought some feedback could be nice :)

Good luck with this project!

**Comment by jywarren** [comment]
Fixed! Also, try double clicking the ants or dragging them.

**Comment by shaief** [comment]
Thanks! it is beautiful now :)

**Comment by shaief** [comment]
After about 24 hours with the new version:
![ant_farm_-_2015-08-06_08 33 25](https://cloud.githubusercontent.com/assets/899702/9104497/df656130-3c15-11e5-9321-6faec321cf21.png)

I love it :)

**Comment by jywarren** [comment]
amazing!!
